# Generated by Django 5.2.17 on 2026-09-16 09:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "incident_id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("transaction_id", models.CharField(max_length=100)),
                ("merchant_id", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=10)),
                ("expected_value", models.BigIntegerField(default=0)),
                ("actual_value", models.BigIntegerField(default=0)),
                ("difference", models.BigIntegerField(default=0)),
                ("status", models.CharField(default="OPEN", max_length=20)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("last_detected_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("assigned_to_reference", models.CharField(blank=True, max_length=100)),
                ("condition_present", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "status", "-detected_at"],
                        name="reconciliat_organiz_004fdb_idx",
                    ),
                    models.Index(
                        fields=["organization", "transaction_id"],
                        name="reconciliat_organiz_54af81_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "transaction_id", "type"),
                        name="unique_incident_rule",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IncidentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity",
                        to="reconciliation.incident",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("organization", models.CharField(max_length=100)),
                ("transaction_id", models.CharField(max_length=100)),
                ("merchant_id", models.CharField(max_length=100)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("status", models.CharField(max_length=30)),
                ("payment_method", models.CharField(max_length=30)),
                ("refunded_minor", models.BigIntegerField(default=0)),
                ("settlement_count", models.PositiveIntegerField(default=0)),
                ("settlement_completed", models.BooleanField(default=False)),
                ("refund_count", models.PositiveIntegerField(default=0)),
                ("failed_refund_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("source_updated_at", models.DateTimeField()),
                ("reconciled_at", models.DateTimeField(auto_now=True)),
                ("snapshot", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "created_at"], name="reconciliat_organiz_c1d18f_idx"
                    ),
                    models.Index(
                        fields=["organization", "merchant_id"],
                        name="reconciliat_organiz_0eed54_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"], name="reconciliat_organiz_39403a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "transaction_id"), name="unique_tenant_payment"
                    )
                ],
            },
        ),
    ]
