import mongoose, {Schema} from 'mongoose';
const common={timestamps:true,versionKey:false} as const;
const org={type:String,required:true,index:true};
const money={type:Number,required:true,min:0,validate:Number.isSafeInteger};
export const roles=['ADMIN','ENGINEER','OPERATIONS','FINANCE','VIEWER'] as const;
export const statuses=['CREATED','PENDING','AUTHORIZED','SUCCESS','FAILED','REFUNDED','PARTIALLY_REFUNDED'] as const;
export const Organization=mongoose.model('Organization',new Schema({organization:{...org,unique:true},name:{type:String,required:true}},common));
export const User=mongoose.model('User',new Schema({userId:{type:String,required:true,unique:true},organization:org,email:{type:String,required:true,unique:true},name:{type:String,required:true},passwordHash:{type:String,required:true,select:false},role:{type:String,enum:roles,required:true},demo:{type:Boolean,default:false}},common));
const sessionSchema=new Schema({sessionId:{type:String,unique:true,required:true},userId:{type:String,required:true},expiresAt:{type:Date,required:true},csrf:{type:String,required:true}},common);
sessionSchema.index({expiresAt:1},{expireAfterSeconds:0});
export const Session=mongoose.model('Session',sessionSchema);
const merchantSchema=new Schema({merchantId:{type:String,required:true,unique:true},organization:org,name:{type:String,required:true},email:{type:String,required:true},status:{type:String,enum:['ACTIVE','SUSPENDED'],default:'ACTIVE'},settlementAccountReference:{type:String,required:true}},common);
merchantSchema.index({organization:1,createdAt:-1});
export const Merchant=mongoose.model('Merchant',merchantSchema);
const transactionSchema=new Schema({transactionId:{type:String,required:true,unique:true},organization:org,merchantId:{type:String,required:true},customerReference:{type:String,required:true},amountMinor:money,currency:{type:String,default:'INR'},paymentMethod:{type:String,enum:['CARD','UPI','NET_BANKING','WALLET'],required:true},status:{type:String,enum:statuses,default:'CREATED'},gateway:{type:String,default:'LENS_SIM'},gatewayReference:{type:String,required:true},refundedMinor:{...money,default:0},reservedRefundMinor:{...money,default:0},ledgerDebitMinor:{...money,default:0},merchantCreditMinor:{...money,default:0},refundLedgerMinor:{...money,default:0},settlementDueAt:{type:Date,required:true}},common);
transactionSchema.index({organization:1,createdAt:-1});
transactionSchema.index({organization:1,status:1,createdAt:-1});
transactionSchema.index({organization:1,merchantId:1,createdAt:-1});
transactionSchema.index({organization:1,gatewayReference:1});
export const Payment=mongoose.model('Payment',transactionSchema);
const eventSchema=new Schema({eventId:{type:String,required:true,unique:true},organization:org,transactionId:{type:String,required:true},eventType:{type:String,required:true},timestamp:{type:Date,default:Date.now},source:{type:String,required:true},metadata:{type:Schema.Types.Mixed,default:{}},correlationId:String},common);
eventSchema.index({organization:1,transactionId:1,timestamp:1});
export const Event=mongoose.model('Event',eventSchema);
const refundSchema=new Schema({refundId:{type:String,required:true,unique:true},organization:org,transactionId:{type:String,required:true},amountMinor:money,reason:{type:String,required:true},status:{type:String,enum:['PENDING','PROCESSING','SUCCESS','FAILED'],default:'PENDING'},createdBy:{type:String,required:true},idempotencyKey:{type:String,required:true},fingerprint:{type:String,required:true}},common);
refundSchema.index({organization:1,idempotencyKey:1},{unique:true});
refundSchema.index({organization:1,transactionId:1,createdAt:-1});
export const Refund=mongoose.model('Refund',refundSchema);
const webhookSchema=new Schema({eventId:{type:String,required:true,unique:true},organization:org,type:{type:String,required:true},fingerprint:{type:String,required:true}},common);
export const Webhook=mongoose.model('Webhook',webhookSchema);
const jobSchema=new Schema({jobId:{type:String,required:true,unique:true},organization:org,kind:{type:String,enum:['PAYMENT','REFUND','SETTLEMENT','RECONCILE'],required:true},state:{type:String,enum:['QUEUED','PROCESSING','COMPLETED','FAILED'],default:'QUEUED'},payload:{type:Schema.Types.Mixed,required:true},progress:{type:Number,default:0},attempts:{type:Number,default:0},error:String,createdBy:String},common);
jobSchema.index({state:1,createdAt:1}); jobSchema.index({organization:1,createdAt:-1});
export const Job=mongoose.model('Job',jobSchema);
const settlementSchema=new Schema({settlementId:{type:String,required:true,unique:true},organization:org,merchantId:{type:String,required:true},period:{type:String,required:true},grossAmountMinor:money,feesMinor:money,netAmountMinor:money,transactionCount:{type:Number,required:true},status:{type:String,enum:['PENDING','PROCESSING','COMPLETED','FAILED'],default:'PENDING'},completedAt:Date},common);
settlementSchema.index({organization:1,createdAt:-1});
export const Settlement=mongoose.model('Settlement',settlementSchema);
const rowSchema=new Schema({organization:org,settlementId:{type:String,required:true},rowNumber:{type:Number,required:true},transactionId:{type:String,required:true},merchantId:{type:String,required:true},amountMinor:money,settlementAmountMinor:money,status:{type:String,required:true},settledAt:{type:Date,required:true}},common);
rowSchema.index({organization:1,settlementId:1,rowNumber:1},{unique:true}); rowSchema.index({organization:1,transactionId:1});
export const SettlementRow=mongoose.model('SettlementRow',rowSchema);
const auditSchema=new Schema({auditId:{type:String,required:true,unique:true},organization:org,actor:{type:String,required:true},action:{type:String,required:true},entityType:{type:String,required:true},entityId:{type:String,required:true},metadata:{type:Schema.Types.Mixed,default:{}}},common);
auditSchema.index({organization:1,createdAt:-1}); auditSchema.index({organization:1,entityId:1,createdAt:-1});
export const Audit=mongoose.model('Audit',auditSchema);
export async function connect(){await mongoose.connect(configUri());await Promise.all(Object.values(mongoose.models).map(m=>m.init()));}
function configUri(){if(!process.env.MONGODB_URI)throw new Error('MONGODB_URI required');return process.env.MONGODB_URI;}
